### ISSUE TITLE
Support Python 3.6

### ISSUE THREAD

**Issue by peci1** [botblox/botblox-manager-software#33]
The tool currently requires Python 3.7 or even 3.8. The readme of this package states 3.6+ is required. And I really vouch for supporting 3.6 as that is the default version on Ubuntu 18.04 which still has 2 years of support ahead.

Also, the readme says the installation command is `pip install botblox`. This command is almost never correct (except when used in a virtualenv, which is however described after this command). On some systems, `pip` will denote the Python 2 pip. These systems know Python 3's pip as `pip3`. To avoid any confusion, the safest way to always get Python3 pip is `python3 -m pip`. Also, I would suggest to either prepend the command with `sudo`, add the `--user` or move the virtualenv specs directly to the installation section.

This is what I get running on Python 3.6:

```
$ python3.6 -m manager
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/peci1/.local/lib/python3.6/site-packages/manager/__main__.py", line 12, in <module>
    main()
  File "/home/peci1/.local/lib/python3.6/site-packages/manager/__main__.py", line 8, in main
    cli()
  File "/home/peci1/.local/lib/python3.6/site-packages/manager/cli.py", line 82, in cli
    required=True,
  File "/usr/lib/python3.6/argparse.py", line 1716, in add_subparsers
    action = parsers_class(option_strings=[], **kwargs)
```

**Comment by AaronElijah** [comment]
Thanks for raising this issue - indeed I'll investigate. 

For reference, I use Ubuntu 20.04 and macOS Big Sur for development (both of which use `python3.8`). Interestingly when I use `pip` it is using the Python 3 version but you're right that not everyone will have that alias to `pip3`

**Comment by AaronElijah** [comment]
Closing this issue as it is currently merged as of https://github.com/botblox/botblox-manager-software/pull/39
