### ISSUE TITLE
Rename the python module

### ISSUE THREAD

**Issue by peci1** [botblox/botblox-manager-software#34]
Python module called `manager` is quite a generic name. Could you please rename it to something that is less prone to name clashes with other packages?

**Comment by AaronElijah** [comment]
Sure I can see there may be a namespace issue there. 

Candidates:
- `cli_config`
- `ip175g_config`
- `ip175g`

Am very much open to suggestions

**Comment by peci1** [comment]
What about just `botblox` or `botblox_config`?

**Comment by AaronElijah** [comment]
Out of the two, I'd say `botblox_config` - with the proviso that it could contain sub-directories for all other boards (when we implement them into this software)

**Comment by AaronElijah** [comment]
Closed by #44
