### ISSUE TITLE
Improve docs

### ISSUE THREAD

**Issue by peci1** [botblox/botblox-manager-software#37]
https://botblox.atlassian.net/wiki/spaces/HARDWARE/pages/34373710/BotBlox+Manager+configuration+documentation is talking about `portmirror` command, but the latest master branch has `mirror` command.

Also, the `Example` column contents are weird. Now it contains:

> `<Base command> <Base positional argument {vlan}> --group 1 2 --group 3 4`

Why not

> `botblox vlan --group 1 2 --group 3 4`

?

**Comment by AaronElijah** [comment]
Thank you. Changed
